vet/config/routes.rb
Rails.application.routes.draw do
  resources :receptionists
  resources :users

end

vet/app/models/receptionist.rb
class Receptionist < ActiveRecord::Base
    belongs_to :user
    
    validates :date, :length => { :maximum => 1 }
    validates :pet, :length => { :maximum => 1 }
    validates :customer, :length => { :maximum => 1 }
    validates :reason, :length => { :maximum => 1 }
end

vet/app/models/user.rb
class User < ActiveRecord::Base
    has_many :date
end

vet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

vet/app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  before_action :set_receptionist, only: [:show, :edit, :update, :destroy]

  # GET /receptionists
  # GET /receptionists.json
  def index
    @receptionists = Receptionist.all
  end

  # GET /receptionists/1
  # GET /receptionists/1.json
  def show
  end

  # GET /receptionists/new
  def new
    @receptionist = Receptionist.new
  end

  # GET /receptionists/1/edit
  def edit
  end

  # POST /receptionists
  # POST /receptionists.json
  def create
    @receptionist = Receptionist.new(receptionist_params)

    respond_to do |format|
      if @receptionist.save
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully created.' }
        format.json { render :show, status: :created, location: @receptionist }
      else
        format.html { render :new }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receptionists/1
  # PATCH/PUT /receptionists/1.json
  def update
    respond_to do |format|
      if @receptionist.update(receptionist_params)
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully updated.' }
        format.json { render :show, status: :ok, location: @receptionist }
      else
        format.html { render :edit }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receptionists/1
  # DELETE /receptionists/1.json
  def destroy
    @receptionist.destroy
    respond_to do |format|
      format.html { redirect_to receptionists_url, notice: 'Receptionist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receptionist
      @receptionist = Receptionist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receptionist_params
      params.require(:receptionist).permit(:date, :pet, :customer, :reminder, :reason, :user_id)
    end
end

vet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :address, :city, :state, :state, :zip, :school, :yearsinpractice)
    end
end

vet/app/helpers/application_helper.rb
module ApplicationHelper
end

vet/app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

vet/app/helpers/users_helper.rb
module UsersHelper
end

vet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

vet/app/views/receptionists/_form.html.erb
<%= form_for(@receptionist) do |f| %>
  <% if @receptionist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receptionist.errors.count, "error") %> prohibited this receptionist from being saved:</h2>

      <ul>
      <% @receptionist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= f.text_field :pet %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :reminder %><br>
    <%= f.text_field :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vet/app/views/receptionists/edit.html.erb
<h1>Editing Receptionist</h1>

<%= render 'form' %>

<%= link_to 'Show', @receptionist %> |
<%= link_to 'Back', receptionists_path %>

vet/app/views/receptionists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Receptionists</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Reminder</th>
      <th>Reason</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receptionists.each do |receptionist| %>
      <tr>
        <td><%= receptionist.date %></td>
        <td><%= receptionist.pet %></td>
        <td><%= receptionist.customer %></td>
        <td><%= receptionist.reminder %></td>
        <td><%= receptionist.reason %></td>
        <td><%= receptionist.user_id %></td>
        <td><%= link_to 'Show', receptionist %></td>
        <td><%= link_to 'Edit', edit_receptionist_path(receptionist) %></td>
        <td><%= link_to 'Destroy', receptionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receptionist', new_receptionist_path %>

vet/app/views/receptionists/new.html.erb
<h1>New Receptionist</h1>

<%= render 'form' %>

<%= link_to 'Back', receptionists_path %>

vet/app/views/receptionists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @receptionist.date %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @receptionist.pet %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @receptionist.customer %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @receptionist.reminder %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @receptionist.reason %>
</p>

<p>
  <strong>User:</strong>
  <%= @receptionist.user_id %>
</p>

<%= link_to 'Edit', edit_receptionist_path(@receptionist) %> |
<%= link_to 'Back', receptionists_path %>

vet/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :yearsinpractice %><br>
    <%= f.text_field :yearsinpractice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vet/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

vet/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>State</th>
      <th>Zip</th>
      <th>School</th>
      <th>Yearsinpractice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.state %></td>
        <td><%= user.zip %></td>
        <td><%= user.school %></td>
        <td><%= user.yearsinpractice %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

vet/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

vet/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip %>
</p>

<p>
  <strong>School:</strong>
  <%= @user.school %>
</p>

<p>
  <strong>Yearsinpractice:</strong>
  <%= @user.yearsinpractice %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>